name: Demo to create automatic PR

on:
  push:
    branches-ignore:
      - main

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ github.ref_name }}
          base: main
          title: "Auto pull request ${{ github.ref_name }}"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: |
            This PR merges ${{ github.ref_name }} into main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete branch after PR merge
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged }}
        run: |
          git push origin --delete ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}